// <auto-generated />
using System;
using ArtistManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtistManager.Migrations
{
    [DbContext(typeof(ArtistManagerDbContext))]
    [Migration("20260923171147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistManager.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/artwork1/400/300",
                            Title = "Sunset over the bay",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/artwork2/400/300",
                            Title = "Portrait study",
                            UpdatedAt = new DateTime(2024, 1, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 17, 10, 30, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/artwork3/400/300",
                            Title = "Mountain landscape",
                            UpdatedAt = new DateTime(2024, 1, 17, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/artwork4/400/300",
                            Title = "Abstract composition",
                            UpdatedAt = new DateTime(2024, 1, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 19, 10, 30, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/artwork5/400/300",
                            Title = "Urban street scene",
                            UpdatedAt = new DateTime(2024, 1, 19, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/artwork6/400/300",
                            Title = "Still life with flowers",
                            UpdatedAt = new DateTime(2024, 1, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
