// <auto-generated />
using ArtistManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtistManager.Migrations
{
    [DbContext(typeof(ArtistManagerDbContext))]
    [Migration("20260922175657_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistManager.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://picsum.photos/seed/artwork1/400/300",
                            Title = "Sunset over the bay",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://picsum.photos/seed/artwork2/400/300",
                            Title = "Portrait study",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://picsum.photos/seed/artwork3/400/300",
                            Title = "Mountain landscape",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://picsum.photos/seed/artwork4/400/300",
                            Title = "Abstract composition",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://picsum.photos/seed/artwork5/400/300",
                            Title = "Urban street scene",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://picsum.photos/seed/artwork6/400/300",
                            Title = "Still life with flowers",
                            UserId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
